export const weekly = [
  {
    id: 1,
    value: "Sunday",
    label: "Sunday",
    background: "#E84855",
    color: "white",
  },
  {
    id: 2,
    value: "Monday",
    label: "Monday",
    background: "#476A6F",
    color: "white",
  },
  {
    id: 3,
    value: "Tuesday",
    label: "Tuesday",
    background: "#519E8A",
    color: "white",
  },
  {
    id: 4,
    value: "Wednesday",
    label: "Wednesday",
    background: "#7EB09B",
    color: "white",
  },
  {
    id: 5,
    value: "Thursday",
    label: "Thursday",
    background: "#2B3A67",
    color: "white",
  },
  {
    id: 6,
    value: "Friday",
    label: "Friday",
    background: "#B56B45",
    color: "white",
  },
  {
    id: 7,
    value: "Saturday",
    label: "Saturday",
    background: "#6F686D",
    color: "white",
  },
  {
    id: 8,
    value: "Weekly",
    label: "Weekly",
    isDisabled: true,
  },
];

export const monthly = [
  {
    id: 32,
    value: "Monthly",
    label: "Monthly",
    isDisabled: true,
  },
  {
    id: 1,
    value: 1,
    label: 1,
    background: "#FFD5C2",
    color: "black",
  },
  { id: 2, value: 2, label: 2, background: "#F28F3B", color: "black" },
  { id: 3, value: 3, label: 3, background: "#F26DF9", color: "black" },
  { id: 4, value: 4, label: 4, background: "#A1B0AB", color: "black" },
  { id: 5, value: 5, label: 5, background: "#C3DAC3", color: "black" },
  { id: 6, value: 6, label: 6, background: "#D5ECD4", color: "black" },
  { id: 7, value: 7, label: 7, background: "#99C5B5", color: "black" },
  { id: 8, value: 8, label: 8, background: "#AFECE7", color: "black" },
  { id: 9, value: 9, label: 9, background: "#81F499", color: "black" },
  { id: 10, value: 10, label: 10, background: "#7DCD85", color: "black" },
  { id: 11, value: 11, label: 11, background: "#E39774", color: "black" },
  { id: 12, value: 12, label: 12, background: "#B0A1BA", color: "black" },
  { id: 13, value: 13, label: 13, background: "#A5B5BF", color: "black" },
  { id: 14, value: 14, label: 14, background: "#ABC8C7", color: "black" },
  { id: 15, value: 15, label: 15, background: "#B8E2C8", color: "black" },
  { id: 16, value: 16, label: 16, background: "#BFF0D4 ", color: "black" },
  { id: 17, value: 17, label: 17, background: "#BFC0C0", color: "black" },
  { id: 18, value: 18, label: 18, background: "#F1C40F", color: "black" },
  { id: 19, value: 19, label: 19, background: "#C4CBCA", color: "black" },
  { id: 20, value: 20, label: 20, background: "#C2E1C2", color: "black" },
  { id: 21, value: 21, label: 21, background: "#92AD94", color: "black" },
  { id: 22, value: 22, label: 22, background: "#FED766", color: "black" },
  { id: 23, value: 23, label: 23, background: "#E6AA68", color: "black" },
  { id: 24, value: 24, label: 24, background: "#AAFCB8", color: "black" },
  { id: 25, value: 25, label: 25, background: "#07BEB8", color: "black" },
  { id: 26, value: 26, label: 26, background: "#FFFD98", color: "black" },
  { id: 27, value: 27, label: 27, background: "#BDE4A7", color: "black" },
  { id: 28, value: 28, label: 28, background: "#B3D2B2", color: "black" },
  { id: 29, value: 29, label: 29, background: "#9FBBCC", color: "black" },
  { id: 30, value: 30, label: 30, background: "#FFA69E", color: "black" },
  { id: 31, value: 31, label: 31, background: "#3DCCC7", color: "black" },
];
